import { runResearchBotDemo } from "@agentsafe/core";
import { WalletPanel } from "./WalletPanel";
import { PresentationMode } from "./PresentationMode";

const money = (value: bigint) => `US$ ${(Number(value) / 1_000_000).toLocaleString("pt-BR", { maximumFractionDigits: 2 })}`;

export default function FinancialLab() {
  const demo = runResearchBotDemo(); const radius = demo.blastRadius.policyConstrained;
  return <main className="shell">
    <header className="topbar"><strong>Agent<span>Safe</span></strong><a href="#prova">Ver a prova real ↓</a></header>
    <section className="hero"><p className="eyebrow">MOTOR DE RISCO FINANCEIRO PARA AGENTES DE IA</p><h1>Antes de dar dinheiro a um agente de IA, descubra quanto ele pode perder.</h1><p className="lead">O AgentSafe encontra riscos automaticamente, calcula o <em>Financial Blast Radius</em>, sugere limites e prova que o agente não consegue ultrapassar a autoridade recebida.</p><div className="hero-actions"><a className="primary-link" href="#laboratorio">Ver laboratório guiado</a><span>Funciona com Phantom + Solana Devnet</span></div></section>
    <section className="proof-strip"><div><b>US$ 10.000</b><span>autoridade sem controles</span></div><i>→</i><div><b className="safe">US$ 20/dia</b><span>máximo autorizado pela policy</span></div><i>→</i><div><b className="safe">BLOQUEIO REAL</b><span>quando o agente tenta exceder o limite</span></div></section>
    <PresentationMode />
    <section className="section-intro"><p className="eyebrow">O QUE O AGENTSAFE FAZ</p><h2>Não é uma carteira. É a camada que limita o estrago financeiro de um agente.</h2></section>
    <section className="steps"><article><span>01</span><h3>Descobre riscos</h3><p>Analisa tools, pagamentos e permissões para achar loops de retry, merchants desconhecidos, destinatários novos e ausência de orçamento.</p></article><article><span>02</span><h3>Calcula o Blast Radius</h3><p>Mostra o máximo que o agente poderia comprometer agora — antes e depois das proteções.</p></article><article><span>03</span><h3>Gera e aplica policy</h3><p>Transforma riscos em regras simples: por transação, por tarefa, por dia e aprovação humana.</p></article></section>
    <section className="card radius-card"><div><p className="eyebrow">FINANCIAL BLAST RADIUS</p><h2>De uma exposição aberta para uma autoridade controlada.</h2></div><div className="radius"><div><p>Antes: treasury disponível</p><b className="amount danger">US$ 10.000</b><small>O agente poderia comprometer todo o saldo.</small></div><i>→</i><div><p>Depois: policy ativa</p><b className="amount safe">{money(radius.effectiveMaximumAuthorizedExposureBaseUnits)}/dia</b><small>Limite efetivo, verificável e explicável.</small></div></div><div className="limits"><Metric label="Por transação" value={money(radius.perTransactionExposureBaseUnits)} /><Metric label="Por tarefa" value={money(radius.currentTaskExposureBaseUnits)} /><Metric label="Por dia" value={money(radius.effectiveMaximumAuthorizedExposureBaseUnits)} /><Metric label="Redução" value={`${(demo.blastRadius.reductionBps! / 100).toFixed(1)}%`} tone="safe" /></div></section>
    <section className="two"><div className="card"><p className="eyebrow">RISCOS ENCONTRADOS SEM CONFIGURAÇÃO MANUAL</p><h2>O sistema sabe o que procurar.</h2><div className="findings">{demo.riskFindings.map((finding) => <article key={finding.id}><b>{finding.category}</b><p>{finding.description}</p></article>)}</div></div><div className="card policy-card"><p className="eyebrow">POLICY RECOMENDADA</p><h2>Regras que um operador entende.</h2><ul><li>Máximo de <b>US$ 2</b> por transação</li><li>Máximo de <b>US$ 3</b> por tarefa</li><li>Máximo de <b>US$ 20</b> por dia</li><li>Merchant novo: <b>pedir aprovação</b></li><li>Destinatário novo: <b>bloquear</b></li></ul><p className="muted">Cada regra é rastreável aos riscos encontrados. A policy só fica ativa após revisão do operador.</p></div></section>
    <section className="card timeline"><p className="eyebrow">DECISÕES DETERMINÍSTICAS</p><h2>O mesmo pedido sempre recebe a mesma decisão.</h2><table><thead><tr><th>Ação do agente</th><th>Valor</th><th>Decisão</th></tr></thead><tbody>{demo.timeline.map((event) => <tr key={event.intent.id}><td>{event.label}</td><td>{money(event.intent.amountBaseUnits)}</td><td className={event.decision.decision.toLowerCase()}>{event.decision.decision === "ALLOW" ? "PERMITIR" : event.decision.decision === "DENY" ? "BLOQUEAR" : "PEDIR APROVAÇÃO"}</td></tr>)}</tbody></table></section>
    <section id="prova" className="section-intro proof-title"><p className="eyebrow">PROVA REAL NA SOLANA DEVNET</p><h2>Não basta recomendar: o agente precisa ser incapaz de passar do limite.</h2><p>A demonstração abaixo cria 100 test‑USDC, delega apenas 20 para uma identidade temporária do AgentSafe, permite US$ 0,55 e bloqueia uma tentativa de US$ 21.</p></section><section id="laboratorio"><WalletPanel /></section>
    <footer>AgentSafe mede autoridade financeira no contexto atual. Resultados de risco são simulados; a prova de limite delegado é executada na Solana Devnet.</footer>
  </main>;
}
function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className="metric"><p className="eyebrow">{label}</p><b className={tone}>{value}</b></div>; }
