"use client";
import { useState } from "react";
import { Connection, Keypair, PublicKey, SystemProgram, Transaction, clusterApiUrl } from "@solana/web3.js";
import { ASSOCIATED_TOKEN_PROGRAM_ID, MINT_SIZE, TOKEN_PROGRAM_ID, createApproveInstruction, createAssociatedTokenAccountInstruction, createInitializeMintInstruction, createMintToInstruction, createTransferInstruction, getAssociatedTokenAddress } from "@solana/spl-token";
const connection = new Connection(clusterApiUrl("devnet"), "confirmed"); const ALLOWANCE = 20_000_000n;
type Phantom = { isPhantom?: boolean; connect: () => Promise<{ publicKey: PublicKey }>; signTransaction: (transaction: Transaction) => Promise<Transaction> }; declare global { interface Window { phantom?: { solana?: Phantom } } } type Demo = { agent: Keypair; treasuryToken: PublicKey; agentToken: PublicKey };
export function DevnetProof() { const [owner, setOwner] = useState<PublicKey>(); const [demo, setDemo] = useState<Demo>(); const [status, setStatus] = useState("Conecte uma única carteira Phantom em Devnet para iniciar."); const [busy, setBusy] = useState(false); const wallet = () => window.phantom?.solana;
  async function connect() { const p = wallet(); if (!p?.isPhantom) { setStatus("Phantom não foi encontrado. Abra este site em um navegador com a extensão Phantom ativada."); return; } try { const result = await p.connect(); setOwner(result.publicKey); setStatus("Carteira conectada. A demonstração usa test‑USDC e uma identidade temporária do AgentSafe."); } catch { setStatus("A conexão foi cancelada."); } }
  async function setup() { const p = wallet(); if (!p || !owner) return; setBusy(true); setStatus("Confirme uma transação: token de teste, limite de 20 e identidade temporária do agente."); try { const mint = Keypair.generate(); const agent = Keypair.generate(); const treasuryToken = await getAssociatedTokenAddress(mint.publicKey, owner, false, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID); const agentToken = await getAssociatedTokenAddress(mint.publicKey, agent.publicKey, false, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID); const rent = await connection.getMinimumBalanceForRentExemption(MINT_SIZE, "confirmed"); const tx = new Transaction().add(SystemProgram.createAccount({ fromPubkey: owner, newAccountPubkey: mint.publicKey, space: MINT_SIZE, lamports: rent, programId: TOKEN_PROGRAM_ID }), createInitializeMintInstruction(mint.publicKey, 6, owner), createAssociatedTokenAccountInstruction(owner, treasuryToken, owner, mint.publicKey, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID), createAssociatedTokenAccountInstruction(owner, agentToken, agent.publicKey, mint.publicKey, TOKEN_PROGRAM_ID, ASSOCIATED_TOKEN_PROGRAM_ID), createMintToInstruction(mint.publicKey, treasuryToken, owner, 100_000_000n), SystemProgram.transfer({ fromPubkey: owner, toPubkey: agent.publicKey, lamports: 3_000_000 }), createApproveInstruction(treasuryToken, agent.publicKey, owner, ALLOWANCE)); const latest = await connection.getLatestBlockhash("confirmed"); tx.feePayer = owner; tx.recentBlockhash = latest.blockhash; tx.partialSign(mint); const signed = await p.signTransaction(tx); const signature = await connection.sendRawTransaction(signed.serialize()); await connection.confirmTransaction({ signature, ...latest }, "confirmed"); setDemo({ agent, treasuryToken, agentToken }); setStatus(`Pronto. Foram criados 100 test‑USDC, mas o agente recebeu poder para gastar somente 20. Tx: ${signature}`); } catch (error) { setStatus(`A preparação não foi concluída: ${error instanceof Error ? error.message : "erro desconhecido"}`); } finally { setBusy(false); } }
  async function execute(amount: bigint, label: string) { if (!demo) return; setBusy(true); setStatus(`${label}: enviando a tentativa pela identidade temporária do AgentSafe.`); try { const tx = new Transaction().add(createTransferInstruction(demo.treasuryToken, demo.agentToken, demo.agent.publicKey, amount)); const latest = await connection.getLatestBlockhash("confirmed"); tx.feePayer = demo.agent.publicKey; tx.recentBlockhash = latest.blockhash; tx.sign(demo.agent); const signature = await connection.sendRawTransaction(tx.serialize()); await connection.confirmTransaction({ signature, ...latest }, "confirmed"); setStatus(`${label} confirmado na Devnet. Tx: ${signature}`); } catch (error) { const raw = error instanceof Error ? error.message : "erro desconhecido"; const simple = raw.includes("insufficient funds") ? "O SPL Token Program bloqueou a tentativa: o agente não tem autoridade para 21 test‑USDC. Nenhum token foi movimentado." : raw; setStatus(`${label} bloqueado antes da liquidação. ${simple}`); } finally { setBusy(false); } }
  return <section className="devnet"><div><p className="eyebrow">LABORATÓRIO INTERATIVO</p><h3>Faça a prova em uma carteira só.</h3><p>Não usamos seed phrase. A sua carteira é o treasury; o AgentSafe temporário só existe nesta sessão.</p></div><div className="devnet-actions"><button onClick={connect} disabled={busy}>{owner ? "Carteira conectada" : "1. Conectar Phantom"}</button><button onClick={setup} disabled={!owner || busy}>2. Criar demo de 20 USDC</button><button onClick={() => execute(550_000n, "Pagamento de US$ 0,55")} disabled={!demo || busy}>3. Permitir US$ 0,55</button><button className="danger-button" onClick={() => execute(21_000_000n, "Teste de US$ 21")} disabled={!demo || busy}>4. Bloquear US$ 21</button></div>{owner && <code>{owner.toBase58()}</code>}<p className="devnet-status">{status}</p></section>; }
