"use client";
import { useState } from "react";
import { DevnetProof } from "./DevnetProof";

const steps = ["Quanto esse agente pode perder agora?", "AgentSafe descobre os riscos financeiros automaticamente.", "Os riscos viram limites simples e explicáveis.", "A blockchain impede o agente de passar do limite."];
const events = [["Busca de artigo", "US$ 0,06", "PERMITIR"], ["Nova assinatura", "US$ 0,31", "PERMITIR"], ["Loop de retries", "US$ 14,00", "BLOQUEAR"], ["Merchant desconhecido", "US$ 4,00", "PEDIR APROVAÇÃO"], ["Destinatário novo", "US$ 500,00", "BLOQUEAR"]];

export default function Home() {
  const [step, setStep] = useState(0);
  return <main className="shell"><header><strong>Agent<span>Safe</span></strong><a href="#prova">Ver prova on-chain ↓</a></header>
    <section className="hero"><p className="eyebrow">MOTOR DE RISCO FINANCEIRO PARA AGENTES DE IA</p><h1>Antes de dar dinheiro a um agente de IA, descubra quanto ele pode perder.</h1><p>O AgentSafe encontra riscos, calcula o <em>Financial Blast Radius</em>, recomenda uma policy e limita a autoridade financeira do agente.</p><a className="cta" href="#como-funciona">Entender em 2 minutos</a></section>
    <section className="proof"><div><b>US$ 10.000</b><span>sem controles</span></div><i>→</i><div><b>US$ 20/dia</b><span>policy aplicada</span></div><i>→</i><div><b>BLOQUEIO REAL</b><span>limite excedido</span></div></section>
    <section className="story"><p className="eyebrow">ROTEIRO DE APRESENTAÇÃO · {step + 1}/4</p><h2>{steps[step]}</h2><p>{step === 0 ? "A resposta é o Financial Blast Radius: a maior exposição que o agente tem agora." : step === 1 ? "Detectamos orçamento ausente, retry pago, merchant desconhecido e destinatário novo." : step === 2 ? "Exemplo: US$ 2 por transação, US$ 3 por tarefa e US$ 20 por dia." : "Uma transferência de US$ 0,55 foi permitida na Devnet; a tentativa de US$ 21 foi recusada pelo SPL Token Program."}</p><button onClick={() => setStep((step + 1) % steps.length)}>Próximo passo →</button></section>
    <section id="como-funciona"><p className="eyebrow">COMO FUNCIONA</p><h2>O AgentSafe é o cérebro de risco — não uma wallet.</h2><div className="cards"><article><span>01</span><h3>Descobre</h3><p>Encontra falhas financeiras antes que elas virem prejuízo.</p></article><article><span>02</span><h3>Limita</h3><p>Converte riscos em políticas de valor, tarefa e velocidade.</p></article><article><span>03</span><h3>Impede</h3><p>Faz o agente ser incapaz de gastar além da autoridade recebida.</p></article></div></section>
    <section className="radius"><p className="eyebrow">FINANCIAL BLAST RADIUS</p><h2>US$ 10.000 de exposição viram US$ 20 por dia.</h2><div className="numbers"><div><span>Antes</span><b className="danger">US$ 10.000</b><small>Autoridade sem limite</small></div><i>→</i><div><span>Depois</span><b>US$ 20/dia</b><small>Máximo autorizado</small></div></div><div className="limits"><span>US$ 2 por transação</span><span>US$ 3 por tarefa</span><span>3 retries</span><span>Merchant novo: aprovação</span></div></section>
    <section className="two"><div className="panel"><p className="eyebrow">RISCOS ENCONTRADOS</p><h2>O usuário não precisou configurar isso.</h2><ul><li>Sem orçamento de tarefa</li><li>Loop de retries pagos</li><li>Merchant desconhecido</li><li>Preço anômalo</li><li>Destinatário desconhecido</li></ul></div><div className="panel"><p className="eyebrow">POLICY GERADA</p><h2>Regras que qualquer operador entende.</h2><ul><li>Máximo de US$ 2 por pagamento</li><li>Máximo de US$ 3 por tarefa</li><li>Máximo de US$ 20 por dia</li><li>Destinatário novo: bloquear</li></ul></div></section>
    <section className="panel timeline"><p className="eyebrow">DECISÕES</p><h2>O agente recebe uma decisão antes de gastar.</h2><table><thead><tr><th>Ação</th><th>Valor</th><th>Decisão</th></tr></thead><tbody>{events.map(([action, value, decision]) => <tr key={action}><td>{action}</td><td>{value}</td><td className={decision === "BLOQUEAR" ? "deny" : decision === "PERMITIR" ? "allow" : "approval"}>{decision}</td></tr>)}</tbody></table></section>
    <section id="prova" className="onchain"><p className="eyebrow">PROVA REAL · SOLANA DEVNET</p><h2>Não é apenas uma tela de limites.</h2><p>Uma identidade temporária recebe 20 test‑USDC de autoridade. Um pagamento de US$ 0,55 é permitido. Uma tentativa de US$ 21 é bloqueada antes de movimentar tokens.</p><div><b>✓ Permitido: US$ 0,55</b><b>✓ Bloqueado: US$ 21</b><b>✓ Nenhum token movido no bloqueio</b></div><DevnetProof /></section>
    <footer>AgentSafe · Financial Risk Engine for AI Agents</footer>
  </main>;
}
